version: '3.5'

services:
  adalite-backend:
    container_name: ${COMPOSE_PROJECT_NAME}-adalite-backend
    build: ..
    depends_on:
      - postgres
      - cardano-node
      - cardano-db-sync
      - cardano-submit-api
    ports:
      - ${ADALITE_BACKEND_HOST_PORT}:8080
    command: ["./wait-for-it.sh", "cardano-submit-api:8101", "-t", "3600", "--", "/bin/sh", "-c", "yarn start >> /var/log/app/server.log 2>&1"]
    volumes:
      - ${DATA_PATH}/adalite-backend:/var/log/app
    environment:
      name: ${COMPOSE_PROJECT_NAME}-adalite-backend
      NODE_ENV: production
      PORT: 8080
      DB: ${POSTGRES_DB}
      DB_PORT: 5432
      DB_HOST: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      CORS_ENABLED_FOR: ${CORS_ENABLED_FOR}
      IMPORTER_ENDPOINT: http://localhost:8101/api/submit/tx # TODO/hrafn
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:11.5-alpine
    ports:
      - ${DB_HOST_PORT}:5432
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data
    restart: on-failure

  cardano-node:
    image: inputoutput/cardano-node:master
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - ${DATA_PATH}/node-db:/data/db
      - ${DATA_PATH}/node-ipc:/ipc

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:master
    environment:
      - NETWORK=${NETWORK}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - cardano-node
      - postgres
    volumes:
      - ${DATA_PATH}/node-ipc:/node-ipc
    restart: on-failure

  cardano-explorer-api: # TODO: remove, not used outside testing
    image: inputoutput/cardano-explorer-api:master
    depends_on:
      - postgres
      - cardano-db-sync
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8100:8100
    restart: on-failure

  cardano-submit-api:
    image: inputoutput/cardano-submit-api:master
    environment:
      - NETWORK=${NETWORK}
    depends_on:
      - cardano-node
    volumes:
      - ${DATA_PATH}/node-ipc:/node-ipc
    ports:
      - 8101:8101
    restart: on-failure

volumes:
  postgres:
  node-db:
  node-ipc:
