version: '3'
services:
  adalite-backend:
    container_name: ${COMPOSE_PROJECT_NAME}-adalite-backend
    build: ..
    depends_on:
      - db
      - cardano-http-bridge
      - adalite-importer
    ports:
      - ${ADALITE_BACKEND_HOST_PORT}:8080
    command: ["./wait-for-it.sh", "adalite-importer:8080", "-t", "3600", "--", "/bin/sh", "-c", "yarn start >> /var/log/app/server.log 2>&1"]
    volumes:
      - ${DATA_PATH}/adalite-backend:/var/log/app
    environment:
      name: ${COMPOSE_PROJECT_NAME}-adalite-backend
      NODE_ENV: production
      PORT: 8080
      DB: cardano
      DB_PORT: 5432
      DB_HOST: db
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      CORS_ENABLED_FOR: ${CORS_ENABLED_FOR}
      IMPORTER_URL: http://adalite-importer:8080
      CARDANO_BRIDGE_URL: http://cardano-http-bridge:8082
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
  adalite-importer:
    container_name: ${COMPOSE_PROJECT_NAME}-adalite-importer
    image: refi93/adalite-importer:latest-master-shelley
    ports:
      - "${ADALITE_IMPORTER_HOST_PORT}:8080"
    depends_on:
      - db
      - cardano-http-bridge
    environment:
      NODE_ENV: production
      CARDANO_NETWORK: ${CARDANO_NETWORK}
      CARDANO_BRIDGE_URL: http://cardano-http-bridge:8082
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: cardano
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  cardano-http-bridge:
    container_name: ${COMPOSE_PROJECT_NAME}-cardano-http-bridge
    image: refi93/cardano-http-bridge:latest
    ports:
      - "${HTTP_BRIDGE_HOST_PORT}:8082"
    volumes:
      - ${DATA_PATH}/cardano-http-bridge:/home/docker/data
    environment:
      CARDANO_NETWORK: ${CARDANO_NETWORK}
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:11.5
    ports:
      - ${DB_HOST_PORT}:5432
    volumes:
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cardano

